CREATE TABLE mixers (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE CHECK (name != ''),
  email VARCHAR(255) NOT NULL,
  salt VARCHAR(255) NOT NULL,
  passhash VARCHAR(255) NOT NULL
);