CREATE TABLE vendors (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE CHECK (slug != ''),
  code VARCHAR(10) NOT NULL UNIQUE CHECK (code != ''),
  name VARCHAR(255) NOT NULL UNIQUE CHECK (name != ''),
  url VARCHAR(255)
);